template_path: bridge.yaml
stack_name: bridge
dependencies:
  - prod/essentials.yaml
parameters:
  AwsAccount: {{ environment_variable.TRAVIS_BRANCH }}
  AwsDefaultVpcId: "vpc-9c70bbf9"
  NewRelicAccountId: "754728514883"
  NewRelicExternalId: !ssm /infra/NewRelicExternalId
  OperatorEmail: bridgeops@sagebase.org
  VpcPeeringRequesterAwsAccountId: !ssm /infra/VpcPeeringRequesterAwsAccountId
